# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-04-07 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='calories',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='cholesterol',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(default='consumer', max_length=50),
            preserve_default=False,
        ),
    ]
