# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-04-07 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190407_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='index',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
