# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-04-07 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_profile_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about',
            field=models.CharField(default='heh', max_length=160),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='qrcode',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
