# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-04-07 03:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190407_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='author',
        ),
        migrations.AddField(
            model_name='company',
            name='status',
            field=models.CharField(default='profile', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(default='company', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 4, 7, 3, 47, 53, 656995, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Profile'),
        ),
    ]
