# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-04-07 08:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190407_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_post',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 4, 7, 8, 35, 37, 388578, tzinfo=utc), max_length=50),
        ),
        migrations.AlterField(
            model_name='company_post',
            name='photo',
            field=models.ImageField(default='images/post_default.png', upload_to='images/'),
        ),
    ]
