# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-04-07 08:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20190407_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_post',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 4, 7, 8, 35, 46, 802213, tzinfo=utc), max_length=50),
        ),
    ]
